{% set name = "ioos_qc" %}
{% set version = "2.2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ioos_qc-{{ version }}.tar.gz
  sha256: c18dd4ab0cd752782d272bb950fcd2c198681ea03ff391d7e858b3e4b1634a6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - geographiclib
    - geojson
    - h5netcdf
    - jsonschema
    - numpy >=1.14
    - pandas
    - pyparsing
    - ruamel.yaml
    - scipy
    - shapely
    - xarray

test:
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check
  imports:
    - ioos_qc

outputs:
  - name: ioos_qc
  - name: ioos-qc
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - {{ pin_subpackage("ioos_qc", max_pin="x.x.x") }}
        - python >={{ python_min }}
    test:
      requires:
        - pip
        - python {{ python_min }}
      commands:
        - pip check
      imports:
        - ioos_qc

about:
  home: https://github.com/ioos/ioos_qc
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: |
    Collection of utilities, scripts and tests to assist in automated
    quality assurance and quality control for oceanographic datasets and
    observing systems

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
