{% set name = "ioos_qc" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ioos_qc-{{ version }}.tar.gz
  sha256: 86a43e1b337cd2e0e95960a227fc9f042e6c0d4823ad02ba539bb5d27d12b7a8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
  run:
    - bokeh
    - geographiclib
    - geojson
    - h5netcdf
    - jsonschema
    - numba
    - numpy >=1.14
    - pandas
    - pyparsing
    - ruamel.yaml
    - scipy
    - shapely
    - xarray

test:
  imports:
    - ioos_qc
    - ioos_qc.config_creator
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ioos/ioos_qc
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: |
    Collection of utilities, scripts and tests to assist in automated
    quality assurance and quality control for oceanographic datasets and
    observing systems

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
