{% set version = "2.0.0" %}

package:
  name: ioos_qc
  version: {{ version }}

source:
  url: https://github.com/ioos/ioos_qc/archive/{{ version }}.tar.gz
  sha256: 2141d1e8902385ca203d554c41fe21ddd0b001d4ee90ebe27700671001ad113e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - geojson
    - netcdf4
    - numpy >=1.14
    - pygc
    - ruamel.yaml
    - simplejson
    - xarray

test:
  imports:
    - ioos_qc

about:
  home: https://github.com/ioos/ioos_qc
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: |
    Collection of utilities, scripts and tests to assist in automated
    quality assurance and quality control for oceanographic datasets and
    observing systems

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
    - jessicaaustin
