travis:
  secure:
    BINSTAR_TOKEN: g78Cob1guawlnf9dcj2JfhtNBhi9abDV+02wHqEuZde2UOQ+R4DFg6Ae/rI43wtegcb1fsat+Gerw6+mzCbQuqXm0J3QQv0ASrlJbZ05FGpR3LnH1vL/B/X3J/5/taP5BvxVM5KgDUjDZ/SSueY6ovhaSMjDatUsZ7+opwODsCfRoA8v8NbdVQ0ku/Bqihh1l56Je6KlB0ZNoXf9L4m8LnCSKztwmyxU5/3IeGP1PYONbUaPDLaUHICjN+tB3ATGHRTSsxdvSvxwJq51hDXe+l/vW4VNcxj8qXgeXISB97r1++vUL7VqwaoqCrfuxsz3puGndRSN7S1PvG2F8fQ0+jcLRSu12uTukpdu+87vDH4YWk9+xa40xKRVO7J1a1/nLVtNqytG2hnHKmg/Z7O/qBkNY/KChL9b6Fvw0AEKNi1mET9TDt+rYRMBCFym5p3iZGd1fPAxPwwcFv1ap+TqqkeJZIVGxkxzCBZjOzCnnFIWzaYFE8cP+1w1EHd/rS/4GWraRtrCfoyzLm9UkfDEhIMN+l0zR+TQVIGHDjW607AHO7byMwvwZyZ+q5MOUpiCYHsVv2Pq1FaeBLOLWgfUZiwtYqT/6hR47+ncvTF6i9EFltYfw2PdS5ykB3wRZpXBHAW0FdjDinG2lRmzSHF0UFzgNKNN0/dFcp/f8xcYVK8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
